apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
data:
  entrypoint.sh: |2
    #!/bin/bash
    set -euxo pipefail

    tbot start \
       --data-dir=/var/lib/teleport/bot \
       --destination-dir=/opt/machine-id \
       --token=${TOKEN} \
       --join-method=token \
       --auth-server=${PROXY} \
       --certificate-ttl=8h \
       --oneshot

    tsh --proxy=${PROXY} \
       -i /opt/machine-id/identity \
       bench ssh \
       --duration=${DURATION} \
       root@${NODE} ls
    tsh --proxy=${PROXY} \
       -i /opt/machine-id/identity \
       bench ssh \
       --duration=${DURATION} \
       root@${LABEL} ls
    tsh --proxy=${PROXY} \
       -i /opt/machine-id/identity \
       bench ssh \
       --duration=${DURATION} \
       --random \
       root@all ls